greeting:
  message: "hello"
  name: "quarkus"

"%dev":
  quarkus:
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:mysql://localhost:3306/bukujava
      username: root
      password:
